// <auto-generated />
using System;
using CleanSweep.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanSweep.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403053908_AddIsHiddenToAlbum")]
    partial class AddIsHiddenToAlbum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanSweep.Domain.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CoverMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_media_id");

                    b.Property<string>("CoverThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("cover_thumbnail_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_albums");

                    b.HasIndex("CoverMediaId")
                        .HasDatabaseName("ix_albums_cover_media_id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_albums_family_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_albums_user_id");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.AlbumMedia", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("AlbumId", "MediaId")
                        .HasName("pk_album_media");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("ix_album_media_media_id");

                    b.ToTable("album_media", (string)null);
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<long>("QuotaBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("quota_bytes");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("invite_code");

                    b.Property<DateTimeOffset?>("InviteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invite_expires_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<long>("QuotaBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("quota_bytes");

                    b.HasKey("Id")
                        .HasName("pk_families");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_families_created_by_user_id");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("ix_families_invite_code")
                        .HasFilter("invite_code IS NOT NULL");

                    b.ToTable("families", (string)null);
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.FamilyMedia", b =>
                {
                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<DateTimeOffset>("SharedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shared_at");

                    b.Property<string>("SharedByUserId")
                        .IsRequired()
                        .HasColumnType("character varying(128)")
                        .HasColumnName("shared_by_user_id");

                    b.HasKey("FamilyId", "MediaId")
                        .HasName("pk_family_media");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("ix_family_media_media_id");

                    b.HasIndex("SharedByUserId")
                        .HasDatabaseName("ix_family_media_shared_by_user_id");

                    b.ToTable("family_media", (string)null);
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.FamilyMember", b =>
                {
                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("member")
                        .HasColumnName("role");

                    b.HasKey("FamilyId", "UserId")
                        .HasName("pk_family_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_family_members_user_id");

                    b.ToTable("family_members", (string)null);
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer")
                        .HasColumnName("media_type");

                    b.Property<string>("OriginalBlobPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_blob_path");

                    b.Property<string>("PlaybackBlobPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("playback_blob_path");

                    b.Property<int>("ProcessingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processing_status");

                    b.Property<string>("SourceCodec")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_codec");

                    b.Property<string>("ThumbnailBlobPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("thumbnail_blob_path");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_media_items");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_media_items_hash")
                        .HasFilter("content_hash IS NOT NULL");

                    b.HasIndex("ProcessingStatus")
                        .HasDatabaseName("ix_media_items_pending")
                        .HasFilter("processing_status = 1");

                    b.HasIndex("UserId", "CapturedAt")
                        .HasDatabaseName("ix_media_items_user_captured")
                        .HasFilter("is_deleted = false");

                    b.ToTable("media_items", (string)null);
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.ShareLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_share_links");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("ix_share_links_album_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_share_links_created_by_user_id");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("ix_share_links_media_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_share_links_token");

                    b.ToTable("share_links", (string)null);
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.Album", b =>
                {
                    b.HasOne("CleanSweep.Domain.Entities.MediaItem", "CoverMedia")
                        .WithMany()
                        .HasForeignKey("CoverMediaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_albums_media_items_cover_media_id");

                    b.HasOne("CleanSweep.Domain.Entities.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .HasConstraintName("fk_albums_families_family_id");

                    b.HasOne("CleanSweep.Domain.Entities.AppUser", "User")
                        .WithMany("Albums")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_albums_users_user_id");

                    b.Navigation("CoverMedia");

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.AlbumMedia", b =>
                {
                    b.HasOne("CleanSweep.Domain.Entities.Album", "Album")
                        .WithMany("AlbumMedia")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_album_media_albums_album_id");

                    b.HasOne("CleanSweep.Domain.Entities.MediaItem", "Media")
                        .WithMany("AlbumMedia")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_album_media_media_items_media_id");

                    b.Navigation("Album");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.Family", b =>
                {
                    b.HasOne("CleanSweep.Domain.Entities.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_families_users_created_by_user_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.FamilyMedia", b =>
                {
                    b.HasOne("CleanSweep.Domain.Entities.Family", "Family")
                        .WithMany("SharedMedia")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_media_families_family_id");

                    b.HasOne("CleanSweep.Domain.Entities.MediaItem", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_family_media_media_items_media_id");

                    b.HasOne("CleanSweep.Domain.Entities.AppUser", "SharedBy")
                        .WithMany()
                        .HasForeignKey("SharedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_family_media_users_shared_by_user_id");

                    b.Navigation("Family");

                    b.Navigation("Media");

                    b.Navigation("SharedBy");
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.FamilyMember", b =>
                {
                    b.HasOne("CleanSweep.Domain.Entities.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_members_families_family_id");

                    b.HasOne("CleanSweep.Domain.Entities.AppUser", "User")
                        .WithMany("FamilyMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_family_members_users_user_id");

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.MediaItem", b =>
                {
                    b.HasOne("CleanSweep.Domain.Entities.AppUser", "User")
                        .WithMany("MediaItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_media_items_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.ShareLink", b =>
                {
                    b.HasOne("CleanSweep.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_share_links_albums_album_id");

                    b.HasOne("CleanSweep.Domain.Entities.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_share_links_users_created_by_user_id");

                    b.HasOne("CleanSweep.Domain.Entities.MediaItem", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_share_links_media_items_media_id");

                    b.Navigation("Album");

                    b.Navigation("CreatedBy");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.Album", b =>
                {
                    b.Navigation("AlbumMedia");
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("FamilyMemberships");

                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.Family", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("SharedMedia");
                });

            modelBuilder.Entity("CleanSweep.Domain.Entities.MediaItem", b =>
                {
                    b.Navigation("AlbumMedia");
                });
#pragma warning restore 612, 618
        }
    }
}
